name: Index

on: 
 push:
  branches:
    - "action-to-index"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository 
      uses: actions/checkout@v2

    - name: Run DocSearch Scrapper
      run: |
        docker run \
          -e TYPESENSE_API_KEY=${{ secrets.TYPESENSE_API_KEY }} \
          -e TYPESENSE_HOST="fdzpgxo5jqkuec0sp-1.a1.typesense.net" \
          -e TYPESENSE_PORT="443" \
          -e TYPESENSE_PROTOCOL="https" \
          -e CONFIG="$(cat ./search.config.json | jq -r tostring)" \
          typesense/docsearch-scraper
       



    
